targets:
  $default:
    builders:
      responsive_config:
        enabled: true
        options:
          tablet_breakpoint: 640
          widescreen_breakpoint: 2100
    sources:
      exclude:
        - test/concept/**
        