include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - /**.g.dart
    - test/**.g.dart
  errors:
    sort_constructors_first: warning
    sort_unnamed_constructors_first: warning
    prefer_int_literals: warning
    prefer_final_locals: warning
    avoid_bool_literals_in_conditional_expressions: warning
    avoid_void_async: warning
    cancel_subscriptions: warning
    invariant_booleans: warning
    unnecessary_await_in_return: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_parenthesis: warning
    unnecessary_raw_strings: warning
    unnecessary_statements: warning

linter:
  rules:
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_positional_boolean_parameters
    - avoid_returning_this
    - avoid_slow_async_io
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - invariant_booleans
    - join_return_with_assignment
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - only_throw_errors
    - parameter_assignments
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_single_quotes
    - throw_in_finally
    - unnecessary_await_in_return
    - unnecessary_null_aware_assignments
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_named_constants
    - use_setters_to_change_properties
    - use_string_buffers
    - unnecessary_lambdas
    - avoid_redundant_argument_values
    - public_member_api_docs
    - package_api_docs
    - type_annotate_public_apis