name: responsive_config
version: 0.1.5
description: >-
  Code generation package, that allows generating 
  responsive classes and responsive variables with annotations.
repository: https://github.com/marcsanny/responsive-config

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_annotation: ^0.1.0
  source_gen: ^1.2.1
  analyzer: ^3.4.1
  build: ^2.2.1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  import_sorter: ^4.6.0

flutter:

import_sorter:
  comments: false
