name: responsive_config
description: Flutter Responsive code generation package.
version: 0.0.1
repository: https://github.com/marcsanny/responsive-config

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_annotation: ^0.0.2
  analyzer: ^3.4.1
  build: ^2.2.1
  source_gen: ^1.2.1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  import_sorter: ^4.6.0

import_sorter:
  comments: false