name: responsive_annotation
description: >-
  Annotations that supports responsive code generation via 
  the `responsive_config` package.
version: 0.0.2
repository: https://github.com/marcsanny/responsive-config

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  import_sorter: ^4.6.0

import_sorter:
  comments: false
  

